language: python
python:
  - "3.8"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
script:
  - python -m pytest backend/tests/
  - python -m pytest --cov backend/tests/

after_success:
  - coveralls
